### ISSUE TITLE
Общая настройка пути к драйверам 

### ISSUE THREAD

**Issue by czen** [Kate2017pro/BRS_Test_main#3]
Чтобы не менять все `System.setProperty("webdriver.chrome.driver", "D:\\MyWork\\Drivers\\chromedriver.exe");`  и `//private String ChromeDriver="D:\\MyWork\\Drivers\\chromedriver.exe";`

**Comment by Kate2017pro** [comment]
Сделано чтение конфиг файла из корня проекта, где хранятся пути к драйверам.

**Comment by czen** [comment]
стоит добавить в config.ini путь к сайту для тестов, т.е.
 testgrade.sfedu.ru или grade/ и т.п.

**Comment by Kate2017pro** [comment]
Путь и возможность такая добавлены. Но лучше сейчас не экспериментировать, тем более, что нужно переделывать пароли или указывать новых юзеров
